### ISSUE TITLE
[FEATURE]: CI: add linting to CI and linting config for consistency

### ISSUE THREAD

**Issue by Tgenz1213** [feder-cr/Jobs_Applier_AI_Agent_AIHawk#875]
### Feature summary

Add ruff linting to CI

### Feature description

Requested changes:

- Pre-config is intended to help developers catch issues that will be inevitably caught during CI. Linting in CI guarantees checking across all future PRs.
- Add ruff.toml for consistent config across local development (add to requirements?), pre-commit, and CI. 

Recommended changes:
- Add ruff.toml
```toml
# shared config for local, pre-commit, and CI step
line-length = 120

[linting]
# rules that we start checking in the future
```
- Modify pre-commit
```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
    - id: ruff
      args: [--fix]
```
- Modify ci.yml to add linting
```yaml
- run: pip install ruff
- run: ruff check --config ruff.toml .
```

### Motivation

Enforce project's coding standards automatically 

### Additional context

Please assign this issue to me when development should start
